POST http://localhost:3000/api/contrat/add
Content-Type: application/json

{    
      "dateContrat": "2018-01-01",
      "customerId":"",
      "dressId":"",
      "beautyServices":["62a24710c2fdc3ef94a8ccde","62a24710c2fdc3ef94a8ccde","62a24710c2fdc3ef94a8ccde"],
      "observation":"observation"
}



###
POST http://localhost:3000/api/process/:id
Content-Type: application/json

{
  "action": "PROCESS_CONTRACT",
  "userId": "62a24710c2fdc3ef94a8ccde",

}
