POST http://localhost:3000/api/events
Content-Type: application/json

{
      "scheduleRentDate": "2018-01-01",
      "rentPrice": "3100",
      "customerId": "62a24710c2fdc3ef94a8ccde",
      "userId": "62a24710c2fdc3ef94a8ccde",
      "dresseId": "62a24710c2fdc3ef94a8ccde", 
      "bServiceId": "62a24710c2fdc3ef94a8ccde",
      "observation":"observation"
    }
}
