version: '3'
services:
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"   
        volumes:
        - ./config/redis.conf:/redis.conf
        - ./data/redis:/data
        command: [ "redis-server", "/redis.conf" ]
